package com.netizen.cms.api.common.enums;

public enum Folder {

	CMS_LOGO, MEMBER, SPEAKER_PHOTO, NOTICE, SYLLABUS, DRESS, PHOTO_GALLERY, DOWNLOAD_CORNER, ABOUTUS, BOOK_INFO,
	ADMISIA_CORE_CONFIG,ADMISIA_CLASS_CONFIG,ADMISIA_APPLICANT

}
